---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cdnmap-deployment
spec:
  selector:
    matchLabels:
      app: cdnmap
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: cdnmap
    spec:
      containers:
      - name: cdnmap
        image: csaregistry.azurecr.io/cdnmap:0.1
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: azureregistrykey
 
---
apiVersion: v1
kind: Service
metadata:
  name: cdnmap
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: cdnmap

